name: flutter_animations
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  fonts:
    - family: Jost
      fonts:
        - asset: fonts/Jost/Jost-Italic-VariableFont_wght.ttf
        - asset: fonts/Jost/Jost-VariableFont_wght.ttf
          weight: 800

  uses-material-design: true

